import { Product } from 'types';

export const mockProducts: Product[] = [
  {
    _id: '1',
    name: 'Truffle Pasta Delight',
    description: 'Creamy pasta with black truffle, parmesan, and fresh herbs',
    price: 28.99,
    image: 'https://www.cucinabyelena.com/wp-content/uploads/2022/10/0Z4A4306-2-e1666648982620.jpg',
    category: 'Main Course',
    rating: 4.8,
    cookingTime: '25 min',
    ingredients: ['Pasta', 'Black Truffle', 'Parmesan', 'Cream', 'Herbs'],
    isVegetarian: true,
    isSpicy: false,
  },
  {
    _id: '2',
    name: 'Spicy Dragon Roll',
    description: 'Fresh salmon, avocado, cucumber with spicy mayo and eel sauce',
    price: 16.99,
    image: 'https://www.justonecookbook.com/wp-content/uploads/2020/06/Dragon-Roll-0286-I.jpg',
    category: 'Sushi',
    rating: 4.9,
    cookingTime: '15 min',
    ingredients: ['Salmon', 'Avocado', 'Cucumber', 'Spicy Mayo', 'Nori'],
    isVegetarian: false,
    isSpicy: true,
  },
  {
    _id: '3',
    name: 'Wagyu Beef Burger',
    description: 'Premium wagyu beef with caramelized onions and truffle aioli',
    price: 34.99,
    image:
      'https://www.seriouseats.com/thmb/P0opRA7Movx8bqIAjXQHo7y6VeU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/20230525-SEA-Wagyu-Burger-Amanda-Suarez-hero-54009c50b715486892bbed7a0edc829c.jpg',
    category: 'Burgers',
    rating: 4.7,
    cookingTime: '20 min',
    ingredients: ['Wagyu Beef', 'Brioche Bun', 'Truffle Aioli', 'Caramelized Onions'],
    isVegetarian: false,
    isSpicy: false,
  },
  {
    _id: '4',
    name: 'Mediterranean Quinoa Bowl',
    description: 'Healthy quinoa with roasted vegetables, feta, and tahini dressing',
    price: 18.99,
    image: 'https://pinchofyum.com/wp-content/uploads/Mediterranean-Bowl-Recipe.jpg',
    category: 'Healthy',
    rating: 4.6,
    cookingTime: '18 min',
    ingredients: ['Quinoa', 'Roasted Vegetables', 'Feta Cheese', 'Tahini', 'Olives'],
    isVegetarian: true,
    isSpicy: false,
  },
  {
    _id: '5',
    name: 'Chocolate Lava Cake',
    description: 'Warm chocolate cake with molten center, served with vanilla ice cream',
    price: 12.99,
    image:
      'https://www.foodnetwork.com/content/dam/images/food/fullset/2014/2/19/1/WU0701H_Molten-Chocolate-Cakes_s4x3.jpg',
    category: 'Desserts',
    rating: 4.9,
    cookingTime: '12 min',
    ingredients: ['Dark Chocolate', 'Butter', 'Eggs', 'Flour', 'Vanilla Ice Cream'],
    isVegetarian: true,
    isSpicy: false,
  },
  {
    _id: '6',
    name: 'Thai Green Curry',
    description: 'Authentic Thai green curry with coconut milk and fresh basil',
    price: 22.99,
    image: 'https://hot-thai-kitchen.com/wp-content/uploads/2022/04/green-curry-new-sq-3.jpg',
    category: 'Asian',
    rating: 4.8,
    cookingTime: '30 min',
    ingredients: ['Green Curry Paste', 'Coconut Milk', 'Chicken', 'Thai Basil', 'Jasmine Rice'],
    isVegetarian: false,
    isSpicy: true,
  },
];
